### ISSUE TITLE
Reason for Appveyor build fail I think

### ISSUE THREAD

**Issue by masalmon** [masalmon/Ropenaq#13]
https://github.com/krlmlr/r-appveyor/issues/57

And somehow I was not able to change my config file correctly.

**Comment by krlmlr** [comment]
Try in appveyor.yml:

```
environment:
  global:
    WARNINGS_ARE_ERRORS: 1

  matrix:
  - R_VERSION: release
    R_ARCH: x64

  - R_VERSION: patched
```
